# -*- coding: utf-8 -*-
# black: skip file
"""
CodeGemmaTransformer.py

GENERATED BY METAPROJECT.
"""
# import os
import unittest
# from unittest.mock import MagicMock

# pylint: disable=unused-import
from tests.generated.test_code_gemma_transformer import (
    TestCodeGemmaTransformer as GeneratedTestCodeGemmaTransformer
)

from llm.extension.code_gemma_transformer import (
    CodeGemmaTransformer
)

from tests.extension import shared_test_methods
from tests.extension.base_test_class import BaseTestClass


class TestCodeGemmaTransformer(BaseTestClass):
    """
    Test cases for CodeGemmaTransformer class.
    """

    def test_transformer_has_correct_values(self):
        """
        Test the get_tokenizer method of BertTransformer class.
        """
        obj = CodeGemmaTransformer()
        self.assertEqual(obj.transformers_model_name, "google/codegemma-2b")
        self.assertEqual(obj.model_type, "AutoModelForCausalLM")
        self.assertEqual(obj.tokenizer_type, "GemmaTokenizer")


if __name__ == '__main__':
    unittest.main()
