# -*- coding: utf-8 -*-
# black: skip file
"""
SalesforceTransformer.py

GENERATED BY METAPROJECT.
"""
# import os
import unittest
# from unittest.mock import MagicMock

# pylint: disable=unused-import
from tests.generated.test_salesforce_transformer import (
    TestSalesforceTransformer as GeneratedTestSalesforceTransformer
)

from llm.extension.salesforce_transformer import (
    SalesforceTransformer
)

from tests.extension import shared_test_methods
from tests.extension.base_test_class import BaseTestClass


class TestSalesforceTransformer(BaseTestClass):
    """
    Test cases for SalesforceTransformer class.
    """

    def test_transformer_has_correct_values(self):
        """
        Test the get_tokenizer method of BertTransformer class.
        """
        obj = SalesforceTransformer()
        self.assertEqual(obj.transformers_model_name, "Salesforce/codegen-350M-mono")
        self.assertEqual(obj.model_type, "AutoModelForCausalLM")
        self.assertEqual(obj.tokenizer_type, "AutoTokenizer")


if __name__ == "__main__":
    unittest.main()
