# -*- coding: utf-8 -*-
# black: skip file
"""
BertTransformer.py

GENERATED BY METAPROJECT.
"""
#import os
import unittest
#from unittest.mock import MagicMock

# pylint: disable=unused-import
from tests.generated.test_bert_transformer import (
    TestBertTransformer as GeneratedTestBertTransformer
)

from llm.extension.bert_transformer import (
    BertTransformer
)

from tests.extension import shared_test_methods
from tests.extension.base_test_class import BaseTestClass

class TestBertTransformer(BaseTestClass):
    """
    Test cases for BertTransformer class.
    """
    def test_initialize(self):
        """
        Test the initialization of the BertTransformer class.

        NOTE: this is already done in generated model. Start by writing
        better test for this class.
        """
        obj = BertTransformer()
        self.assertTrue(obj)

if __name__ == '__main__':
    unittest.main()
