# -*- coding: utf-8 -*-
# black: skip file
"""
CodeGemmaTransformer.py

GENERATED BY METAPROJECT.
"""
#import os
import unittest
#from unittest.mock import MagicMock

# pylint: disable=unused-import
from tests.generated.test_code_gemma_transformer import (
    TestCodeGemmaTransformer as GeneratedTestCodeGemmaTransformer
)

from llm.extension.code_gemma_transformer import (
    CodeGemmaTransformer
)

from tests.extension import shared_test_methods
from tests.extension.base_test_class import BaseTestClass

class TestCodeGemmaTransformer(BaseTestClass):
    """
    Test cases for CodeGemmaTransformer class.
    """
    def test_initialize(self):
        """
        Test the initialization of the CodeGemmaTransformer class.

        NOTE: this is already done in generated model. Start by writing
        better test for this class.
        """
        obj = CodeGemmaTransformer()
        self.assertTrue(obj)

if __name__ == '__main__':
    unittest.main()
