# -*- coding: utf-8 -*-
# black: skip file
"""
BaseTransformer.py

GENERATED BY METAPROJECT.
"""
#import os
import unittest
#from unittest.mock import MagicMock

# pylint: disable=unused-import
from tests.generated.test_base_transformer import (
    TestBaseTransformer as GeneratedTestBaseTransformer
)

from llm.extension.base_transformer import (
    BaseTransformer
)

from tests.extension import shared_test_methods
from tests.extension.base_test_class import BaseTestClass

class TestBaseTransformer(BaseTestClass):
    """
    Test cases for BaseTransformer class.
    """
    def test_initialize(self):
        """
        Test the initialization of the BaseTransformer class.

        NOTE: this is already done in generated model. Start by writing
        better test for this class.
        """
        obj = BaseTransformer()
        self.assertTrue(obj)

if __name__ == '__main__':
    unittest.main()
