"""
CodeGemmaTransformer.py

GENERATED BY METAPROJECT.
"""
import unittest

from llm.extension.code_gemma_transformer import (
    CodeGemmaTransformer
)

# pylint: disable=unused-import
from tests.extension.base_test_class import BaseTestClass
from tests.generated.test_code_gemma_transformer import (
    TestCodeGemmaTransformer as GeneratedTestCodeGemmaTransformer
)


class TestCodeGemmaTransformer(BaseTestClass):
    """
    Test cases for CodeGemmaTransformer class.
    """

    def test_transformer_has_correct_values(self):
        """
        Test the get_tokenizer method of BertTransformer class.
        """
        obj = CodeGemmaTransformer()
        self.assertEqual(obj.transformers_model_name, "google/codegemma-2b")
        self.assertEqual(obj.model_type, "AutoModelForCausalLM")
        self.assertEqual(obj.tokenizer_type, "GemmaTokenizer")


if __name__ == '__main__':
    unittest.main()
