# -*- coding: utf-8 -*-
# black: skip file
"""
SalesforceTransformer.py

GENERATED BY METAPROJECT.
"""
# import os
import unittest
# from unittest.mock import MagicMock

# pylint: disable=unused-import
from tests.generated.test_salesforce_transformer import (
    TestSalesforceTransformer as GeneratedTestSalesforceTransformer
)

from llm.extension.salesforce_transformer import (
    SalesforceTransformer
)

from tests.extension import shared_test_methods
from tests.extension.base_test_class import BaseTestClass


class TestSalesforceTransformer(BaseTestClass):
    """
    Test cases for SalesforceTransformer class.
    """

    def test_initialize(self):
        """
        Test the initialization of the SalesforceTransformer class.

        NOTE: this is already done in generated model. Start by writing
        better test for this class.
        """
        obj = SalesforceTransformer()
        self.assertTrue(obj)
        self.assertEqual(obj.transformer_model_name, "Salesforce/codegen-350M-mono")


if __name__ == "__main__":
    unittest.main()
