"""
BertTransformer.py

GENERATED BY METAPROJECT.
"""
import unittest

from llm.extension.bert_transformer import (
    BertTransformer
)

# pylint: disable=unused-import
from tests.extension.base_test_class import BaseTestClass
from tests.generated.test_bert_transformer import (
    TestBertTransformer as GeneratedTestBertTransformer
)


class TestBertTransformer(BaseTestClass):
    """
    Test cases for BertTransformer class.
    """

    def test_transformer_has_correct_values(self):
        """
        Test the get_tokenizer method of BertTransformer class.
        """
        obj = BertTransformer()
        self.assertEqual(obj.transformers_model_name, "bert-base-uncased")
        self.assertEqual(obj.model_type, "BertModel")
        self.assertEqual(obj.tokenizer_type, "BertTokenizer")

    def test_get_tokenizer(self):
        """
        Test the get_tokenizer method of BertTransformer class.
        """
        obj = BertTransformer()
        tokenizer = obj.get_tokenizer()
        self.assertIsNotNone(tokenizer)
        self.assertEqual(tokenizer.__class__.__name__, "BertTokenizer")

    def test_get_model(self):
        """
        Test the get_model method of BertTransformer class.
        """
        obj = BertTransformer()
        model = obj.get_model()
        self.assertIsNotNone(model)
        self.assertEqual(model.__class__.__name__, "BertModel")


if __name__ == '__main__':
    unittest.main()
