classes:
    - name: BaseTransformer
      description: Base transformer class
      attributes:
          - name: transformers_model_name
            type: str
            description: Name of the model to use, e.g. "t5-base" (default)
            access_modifier: protected
            default_value: t5-base
            escape_default: true
            has_default: true
          - name: cache_dir
            type: str
            description: Directory to cache the model files
            access_modifier: protected
            default_value: "/tmp/transformers_cache"
            escape_default: true
            has_default: true
          - name: model_type
            type: str
            description: Type of the model, defaults to "PreTrainedModel"
            access_modifier: protected
            default_value: PreTrainedModel
            escape_default: true
            has_default: true
          - name: tokenizer_type
            type: str
            default_value: PreTrainedTokenizerBase
            description: Type of the tokenizer, defaults to "PreTrainedTokenizerBase"
            access_modifier: protected
            escape_default: true
            has_default: true

    - name: BertTransformer
      description: Transformer class for BERT-based models
      extends:
          - BaseTransformer
      generated_class_extends:
          - BaseTransformer
      attributes:
          - name: transformers_model_name
            type: str
            access_modifier: protected
            default_value: bert-base-uncased
            escape_default: true
            has_default: true
            validation:
                presence: true
                choices:
                    - "bert-base-uncased"
                    - "bert-large-uncased"
                    - "bert-base-cased"
                    - "bert-large-cased"
          - name: model_type
            type: str
            description: Type of the model
            access_modifier: protected
            default_value: BertModel
            escape_default: true
            has_default: true
          - name: tokenizer_type
            type: str
            default_value: BertTokenizer
            description: Type of the tokenizer
            access_modifier: protected
            escape_default: true
            has_default: true

    - name: T5Transformer
      description: Transformer class for T5-based models
      extends:
          - BaseTransformer
      generated_class_extends:
          - BaseTransformer
      attributes:
          - name: transformers_model_name
            type: str
            access_modifier: protected
            default_value: t5-base
            escape_default: true
            has_default: true
            validation:
                presence: true
                choices:
                    - "t5-base"
                    - "t5-large"
                    - "t5-3b"
                    - "t5-11b"
          - name: model_type
            type: str
            description: Type of the model
            access_modifier: protected
            default_value: AutoModelForSeq2SeqLM
            escape_default: true
            has_default: true
          - name: tokenizer_type
            type: str
            default_value: AutoTokenizer
            description: Type of the tokenizer
            access_modifier: protected
            escape_default: true
            has_default: true

    - name: CodeGemmaTransformer
      description: Transformer class for google/codegemma models
      extends:
          - BaseTransformer
      generated_class_extends:
          - BaseTransformer
      attributes:
          - name: transformers_model_name
            type: str
            access_modifier: protected
            default_value: "google/codegemma-2b"
            escape_default: true
            has_default: true
            validation:
                presence: true
                choices:
                    - "google/codegemma-2b"
                    - "google/codegemma-7b"
          - name: model_type
            type: str
            description: Type of the model
            access_modifier: protected
            default_value: AutoModelForCausalLM
            escape_default: true
            has_default: true
          - name: tokenizer_type
            type: str
            default_value: GemmaTokenizer
            description: Type of the tokenizer
            access_modifier: protected
            escape_default: true
            has_default: true

    - name: SalesforceTransformer
      description: Transformer class for Salesforce models
      extends:
          - BaseTransformer
      generated_class_extends:
          - BaseTransformer
      attributes:
          - name: transformers_model_name
            type: str
            access_modifier: protected
            default_value: "Salesforce/codegen-350M-mono"
            escape_default: true
            has_default: true
            validation:
                presence: true
                choices:
                    - "Salesforce/codegen-350M-mono"
          - name: model_type
            type: str
            description: Type of the model
            access_modifier: protected
            default_value: AutoModelForCausalLM
            escape_default: true
            has_default: true
          - name: tokenizer_type
            type: str
            default_value: AutoTokenizer
            description: Type of the tokenizer
            access_modifier: protected
            escape_default: true
            has_default: true
